cart/urls.py
from django.urls import path
from .views import  cart_detail,  cart_add, cart_remove, cart_product_update, cart_one_add

app_name = 'cart'

urlpatterns = [
   path('', cart_detail, name='cart_detail'),
   path('cart_one_add/<int:product_id>/', cart_one_add, name='cart_one_add'),
   # path('checkout', CheckoutView.as_view(), name='CheckoutView'),
   path('add/<int:product_id>/', cart_add, name='cart_add'),
   # path('ajouter-au-panier', cart_add_one_product, name='cart_add_one_product'),
   path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
   path('update/', cart_product_update, name='cart_product_update'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from config import settings
from django.conf.urls.static import static


urlpatterns = [

    path('', include("core.urls")),
    path('', include("business.urls")),
    path('cart/', include("cart.urls")),
    path('orders/', include("order.urls")),
    path('coupons/', include("coupons.urls")),
    path('delivery/', include("delivery.urls")),
    # path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    # path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),
    urlpatterns += path('admin/', admin.site.urls),
else:
    urlpatterns += path('sunlab-admin/', admin.site.urls),

delivery/urls.py
from django.urls import path
from .views import  load_communes, delivery_cost 
app_name ='delivery'
urlpatterns = [
   path('load-communes/', load_communes, name='load_communes'),
   path('delivery_cost/', delivery_cost, name='delivery_cost'),
   #  path('vapecity/', views.vapecity, name='vapecity'),
   #  path('contact/', views.ContactView.as_view(), name='ContactView'),
]

order/urls.py
from django.urls import path
from .views import  order_create, admin_order_detail ,admin_order_pdf, order_create_one_product

app_name = 'order'

urlpatterns = [
   path('commander', order_create, name='order_create'),
   path('acheter/<int:product_id>/', order_create_one_product, name='order_create_one_product'),
   path('admin/order/<int:order_id>/', admin_order_detail, name='admin_order_detail'),
   path('admin/order/<int:order_id>/pdf/', admin_order_pdf, name='admin_order_pdf'),

]

order/forms.py
from django import forms 
from django.forms import NumberInput
# from django.core import validators
from .models import Order
from delivery.models import Commune

DELIVERY_CHOICES =(
    ("DOM", "Livraison à domicil"),
    ("REL", "Livraison à un point de relais"),
    ("SAN", "Sans Livraison"),
)

class OrderCreateForm(forms.ModelForm):
    # quantity = forms.IntegerField(min_value=1)
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'address', 'campany', 'email', 'phone', 'wilaya', 'commune', 'note']
        required = ('first_name', 'last_name',  'phone', 'wilaya', 'commune')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # self.fields['wilaya'] = forms.ModelChoiceField(queryset=Wilaya.objects.all()) 
        # self.fields['commune'] = forms.ModelChoiceField(queryset=Commune.objects.all()) 
        # self.fields['delivery'] = forms.ChoiceField(choices = DELIVERY_CHOICES, required=False)
        self.fields['delivery']=forms.CharField(widget=forms.RadioSelect(choices=DELIVERY_CHOICES))
        self.fields['commune'].queryset = Commune.objects.none()
        # self.fields['quantity'] = forms.IntegerField(min_value=1)

        if 'wilaya' in self.data:
            try:
                wilaya_id = int(self.data.get('wilaya'))
                self.fields['commune'].queryset = Commune.objects.filter(wilaya_id=wilaya_id).order_by('name')
            except (ValueError, TypeError):
                pass
        elif not 'wilaya' in self.data:
            self.fields['commune'].queryset = Commune.objects.none()

class OrderFormWithQuantity(OrderCreateForm):
    def __init__(self, *args, **kwargs):
        super(OrderCreateForm, self).__init__(*args, **kwargs)
        self.fields['quantity'] = forms.IntegerField(min_value=1)

order/views.py
from core.models import Product
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.views.generic import TemplateView
from django.views.decorators.http import require_POST
# Create your views here.
from django.http import HttpResponse
import weasyprint
from .forms import OrderCreateForm, OrderFormWithQuantity
from .models import  OrderItem, Order
from django.contrib.admin.views.decorators import staff_member_required
from django.template.loader import render_to_string
from cart.cart import Cart
from coupons.models import Coupon
from delivery.models import Wilaya, Commune
from business.models import Business
from django.core.mail import EmailMessage
import pprint
from io import BytesIO

def order_create_one_product(request,product_id=None):
    form = OrderFormWithQuantity()
    if request.method == 'POST':
        product = Product.objects.get(id=product_id)
        form = OrderFormWithQuantity(request.POST)
        
        coupon = request.session['coupon_id']
        print('le couson utiliser est : ', coupon)
        # coupon.stock -= 1
        # coupon.used += 1
        # coupon.save()
        # print('le FORMULAIRE', form)
        if form.is_valid():
            cd = form.cleaned_data
            quantity=cd['quantity']
            order = form.save()
            print('le formulaire est valid', quantity)
            # print('ORDER ITEM', order.quantity)
            OrderItem.objects.create(order=order,product=product,price=product.price,quantity=quantity)
            # order = Order.objects.get(id=order)

            subject = f'Commande N°: {order.id}'
            message = f'Chére {order.first_name},\n\n' \
                    f'vous avez passer une commande avec succés' \
                    f'votre identifiant de commande est le: {order.id}'

            response = HttpResponse(content_type='application/pdf' )
            response['Content-Disposition' ] = f'filename=order_{order.id}.pdf'
            business   = Business.objects.last().name
            html = render_to_string('order_pdf.html' , {'order' : order, 'business': business})
            pdf_file = weasyprint.HTML(string=html).write_pdf(response)
            mail = EmailMessage(subject, message, 'inter.taki@gmail.com',[order.email])
            mail.attach(pdf_file,out.getvalue(),'application/pdf')
            mail.send()
            return render(request, 'created.html', {'order': order})
            # print('ORDER ITEM')
            # return render(request, 'created.html', {'order': order})
        else:
            # print('yhnooo')
            return redirect(reverse('core:index'))
    return render(request, 'product-detail.html', { 'form' : form})


#  ORDER CREATE

def order_create(request):
    cart = Cart(request)
    wilayas= Wilaya.objects.all().order_by('name') 
    communes= Commune.objects.all().order_by('name') 
    form = OrderCreateForm()
    
    if cart.__len__() :
        # print('request', request.method)
        if request.method == 'POST':
            form = OrderCreateForm(request.POST)
            # print(form)
            if form.is_valid():
                order = form.save()
                order.delivery_cost = order.wilaya.price
                print('oDELIVERY CHOIXE', order.delivery)
                order.save()
                # print('delivery cost', order.wilaya.price)
                for item in cart:
                    OrderItem.objects.create(order=order,product=item['product'],price=item['price'],quantity=item['quantity'])
                try:
                    coupon_id = request.session['coupon_id']
                    coupon = Coupon.objects.get(id=coupon_id)
                    coupon.stock -= 1
                    coupon.used += 1
                    request.session['coupon_id'] = None
                    coupon.save()
                except:
                    pass
                cart.clear()
                total_price = cart.get_total_price_after_discount()
                total_price_with_delivery = total_price + order.delivery_cost
            
                subject = f'Commande N°: {order.id}'
                message = f'Chére {order.first_name},\n\n vous avez passer une commande avec succés' f'votre identifiant de commande est le: {order.id}'
                try :
                    response = HttpResponse(content_type='application/pdf' )
                    response['Content-Disposition' ] = f'filename=order_{order.id}.pdf'
                    business   = Business.objects.last().name
                    html = render_to_string('order_pdf.html' , {'order' : order, 'business': business})
                    out = BytesIO()
                    pdf_file = weasyprint.HTML(string=html).write_pdf(response)
                    mail = EmailMessage(subject, message, 'inter.taki@gmail.com',[order.email])
                    mail.attach(pdf_file,out.getvalue(),'application/pdf')
                    mail.send()
                    context = {
                        'order': order,
                        # 'products_total': products_total, 
                        'total_price': total_price,
                        'delivery': order.delivery_cost,
                        'total_price_with_delivery': total_price_with_delivery,
                        'pdf_file': pdf_file,
                    }
                    return render(request, 'cart.html', {'cart':cart, 'form' : form, 'wilayas': wilayas, 'communes': communes}) # just examples

                    # return render(request, 'created.html', context)
                except :
                    print('yaw matebaatch')
                # stylesheets=[weasyprint.CSS(str(configs.STATIC_ROOT) + 'css/pdf.css' )]
            else: 
                print('the form is not valid')
                return render(request, 'checkout.html', {'cart':cart, 'form' : form, 'wilayas': wilayas, 'communes': communes})
    return render(request, 'checkout.html', {'cart':cart, 'form' : form, 'wilayas': wilayas, 'communes': communes})
    
    

@staff_member_required
def admin_order_detail(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    return render(request, 'order_detail.html', {'order': order})

@staff_member_required
def admin_order_pdf(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    response = HttpResponse(content_type='application/pdf' )
    response['Content-Disposition' ] = f'filename=order_{order.id}.pdf'
    business   = Business.objects.get(id=1).name
    html = render_to_string('order_pdf.html' , {'order' : order, 'business': business})
    # stylesheets=[weasyprint.CSS(str(configs.STATIC_ROOT) + 'css/pdf.css' )]
    weasyprint.HTML(string=html).write_pdf(response)
    return response


# @staff_member_required
# def admin_order_pdf(request, order_id):
#     order = get_object_or_404(Order, id=order_id)
#     html = render_to_string('pdf.html', {'order': order})
#     response = HttpResponse(content_type='application/pdf')
#     response['Content-Disposition'] = f'filename=order_{order.id}.pdf'
#     # weasyprint.HTML(string=html).write_pdf(response)
#     # ajouter le style plus t ard erreur ???
#     # weasyprint.HTML(string=html).write_pdf(response)

#     html = render_to_string('pdf.html' , {'order' : order})
#     stylesheets=[weasyprint.CSS(configs.STATIC_ROOT + 'css/pdf.css' )]
#     weasyprint.HTML(string=html).write_pdf(response,stylesheets=stylesheets)

#     return response


















# def order_create(request):
#     cart = Cart(request)
#     wilayas= Wilaya.objects.all().order_by('name') 
#     form = OrderFormWithOutQuantity()
    
#     coupon_id = request.session['coupon_id']
#     if coupon_id:
#         coupon = Coupon.objects.get(id=coupon_id)
#         if cart.__len__() :
#             print('request', request.method)
#             if request.method == 'POST':
#                 form = OrderFormWithOutQuantity(request.POST)
#                 if form.is_valid():
#                     print('le formulaire est valid')
#                     order = form.save(commit=False)
#                     order.delivery_cost = order.wilaya.price
#                     print('delivery cost', order.wilaya.price)
#                     for item in cart:
#                         OrderItem.objects.create(order=order,product=item['product'],price=item['price'],quantity=item['quantity'])
#                     coupon.stock -= 1
#                     coupon.used += 1
#                     coupon.save()
#                     # cart.clear()
#                     return render(request, 'created.html', {'order': order})
#         else: 
#             return redirect(reverse('core:IndexView'))
#     else:
#         if cart.__len__() :
#             print('request', request.method)
#             if request.method == 'POST':
#                 form = OrderFormWithOutQuantity(request.POST)
#                 if form.is_valid():
#                     print('le formulaire est valid')
#                     order = form.save()
#                     for item in cart:
#                         OrderItem.objects.create(order=order,product=item['product'],price=item['price'],quantity=item['quantity'])
#                     cart.clear()
#                     total_price = cart.get_total_price_after_discount()
#                     total_price_with_delivery = total_price + order.delivery_cost

#                     context = {
#                         'order': order,
#                            'products_total': products_total, 
#                            'total_price': total_price,
#                            'delivery': order.delivery,
#                            'total_price_with_delivery': total_price_with_delivery
#                     }
#                     return render(request, 'created.html', context)
#     return render(request, 'create.html', {'cart':cart, 'form' : form, 'wilayas': wilayas})

order/templates/checkout.html
{% extends "base.html" %}
{% load static %}
{% block content %}
            <div class="checkout-area pt-60 pb-30">
                <div class="container">
                    <form id="order_form"  method="post" data-communes-url="{% url 'delivery:load_communes' %}">

						{% csrf_token %}

                    <div class="row">
                        <div class="col-12">
                            <div class="coupon-accordion">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-6 col-12">
                                <div class="checkbox-form">
                                    <h3>Livraison Details</h3>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="checkout-form-list">
                                                <label>Nom<span class="required">*</span></label>
                                                <input placeholder=""name="first_name" type="text">
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="checkout-form-list">
                                                <label>Prénom <span class="required">*</span></label>
                                                <input placeholder=""name="last_name" type="text">
                                            </div>
                                        </div>
                                      
                                        <div class="col-md-12">
                                            <div class="checkout-form-list">
                                                <label>Addresse <span class="required">*</span></label>
                                                <input placeholder="Street address"name="address" type="text">
                                            </div>
                                        </div>
                                        <div class="col-md-12">
                                            <div class="checkout-form-list">
                                                <label>Entreprise</label>
                                                <input placeholder="(optional)"name="campany" type="text">
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="country-select clearfix">
                                                <label>Wilaya <span class="required">*</span></label>
                                                <select class="nice-select wide" name="wilaya" id="wilayaId" >
										                                <option class="option" value='' selected>Wilaya</option>
                                                    {% for wilaya in wilayas %}
                                                        <option  value={{wilaya.id}} >{{wilaya.name}}</option>
                                                    {% endfor %}
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="country-select clearfix" id="communesId">
                                                <label>Commune <span class="required">*</span></label>
                                                <select class="nice-select wide" name="commune" id="communesId" required>
            										<option class="option" value='' selected>Communes</option>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="checkout-form-list">
                                                <label>Email Address </label>
                                                <input placeholder=""name="email" type="email">
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="checkout-form-list">
                                                <label>Phone  <span class="required">*</span></label>
                                                <input type="text" name="phone">
                                            </div>
                                        </div>
                                        <div class="col-md-12">
                                            <div class="checkout-form-list">
                                                <label>Note</label>
                                                <textarea placeholder="" name="note" type="text"></textarea>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                        </div>
                        <div class="col-lg-6 col-12">
                            <div class="your-order">
                                <h3>Votre Commande</h3>
                                <div class="your-order-table table-responsive">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th class="cart-product-name">Produit</th>
                                                <th class="cart-product-total">Total</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        {% with total_items=cart|length %}
										{% if total_items > 0 %}
											{% for item in cart %}
												{% with product=item.product %}
                                                <tr class="cart_item">
                                                    <td class="cart-product-name"> <strong class="product-quantity">{{item.quantity}}</strong> x {{product.name}}</td>
                                                    <td class="cart-product-total"><span class="amount">{{item.price}} DZD</span></td>  
                                                  </tr>
												{% endwith %}
										{% endfor %}
										{% else %}
											Vou n'avez pas de produit dans votre panier
										{% endif %}
										{% endwith %}
                                        </tbody>
                                        <tfoot>
                                            <tr class="order-total">
                                                <th>Total</th>
						                        <div><strong class="order-total" id="order_total" data-order-total="{{ cart.get_total_price_after_discount|floatformat:2}}"></strong></div>

                                            </tr>
                                        </tfoot>
                                    </table>
                                </div>
                                <div class="payment-method">
                                    <div class="payment-accordion">
                                        <div id="accordion">
                                          <div class="card">
                                            <div class="card-header" id="#payment-1">
                                              <h5 class="panel-title">
                                                <a class="" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                                  Direct Bank Transfer.
                                                </a>
                                              </h5>
                                            </div>
                                            <div id="collapseOne" class="collapse show" data-parent="#accordion">
                                              <div class="card-body">
                                                <p>Make your payment directly into our bank account. Please use your Order ID as the payment reference. Your order won’t be shipped until the funds have cleared in our account.</p>
                                              </div>
                                            </div>
                                          </div>
                                          <div class="card">
                                            <div class="card-header" id="#payment-2">
                                              <h5 class="panel-title">
                                                <a class="collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                                  Cheque Payment
                                                </a>
                                              </h5>
                                            </div>
                                            <div id="collapseTwo" class="collapse" data-parent="#accordion">
                                              <div class="card-body">
                                                <p>Make your payment directly into our bank account. Please use your Order ID as the payment reference. Your order won’t be shipped until the funds have cleared in our account.</p>
                                              </div>
                                            </div>
                                          </div>
                                          <div class="card">
                                            <div class="card-header" id="#payment-3">
                                              <h5 class="panel-title">
                                                <a class="collapsed" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                                                  PayPal
                                                </a>
                                              </h5>
                                            </div>
                                            <div id="collapseThree" class="collapse" data-parent="#accordion">
                                              <div class="card-body">
                                                <p>Make your payment directly into our bank account. Please use your Order ID as the payment reference. Your order won’t be shipped until the funds have cleared in our account.</p>
                                              </div>
                                            </div>
                                          </div>
                                        </div>
                                        <div class="order-button-payment">
                                            <input value="Place order" type="submit">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    </form>

                </div>
            </div>
            <!--Checkout Area End-->
{% endblock content %}
            

order/templates/order_detail.html
{% extends "admin/base_site.html" %}

{% block title %}
    Order {{ order.id }} {{ block.super }}
{% endblock %}

{% block breadcrumbs %}
    <div class="breadcrumbs">
        <a href="{% url 'admin:index'%}">Home</a> &rsaquo;
        <a href="{% url 'admin:order_order_changelist' %}">Commandes</a>
    </div>
{% endblock %}

{% block content %}
    <h1>Commande {{ order.id }}</h1>
        <ul class="object-tools">
            <li>
            <a href="#" onclick="window.print();">Imprimer</a>
            </li>
        </ul>
    <table>
            <tr>
                <th>Crée</th>
                <td>{{ order.created }}</td>
            </tr>
            <tr>
                    <th>Client</th>
                    <td>{{ order.first_name }} {{ order.last_name }}</td>
            </tr>
            <tr>
                <th>E-mail</th>
                <td><a href="mailto:{{ order.email }}">{{ order.email }}</a></td>
            </tr>
            <tr>
            <th>Adresse</th>
                <td>
                    {{ order.addresse }}
                </td>
            </tr>
            <tr>
                <th>Wilaya</th>
                <td>
                    {{ order.wilaya.name }}
                </td>
            </tr>



            <tr>
                <th>Commune</th>
                <td>
                    {{ order.commune.name }}
                </td>
            </tr>
            <tr>
                <th>Total Panier</th>
                <td>{{ order.get_total_basket}} DA</td>
            </tr>
            {% if order.coupon %}
                <tr>
                    <th>Coupon:</th>
                    <td>"{{order.coupon.code}}"</td>
                </tr>
            {% endif %}
            <tr>
                <th>Réduction</th>
                <td>{{ order.discount}} DA</td>
            </tr>
           
            <tr>
                <th>Livraison</th>
                <td>
                    {{ order.wilaya.price }}
                </td>
            </tr>
            <tr>
                <th>Total </th>
                <td>{{order.get_total_cost}}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{% if order.paid %}Payée{% else %}Non payée{% endif %}</td>
            </tr>
    </table>
       <div class="module">
            <h2>Produits achetés</h2>
        <table style="width:100%">
            <thead>
                <tr>
                    <th>Produit</th>
                    <th>Prix</th>
                    <th>Quantité</th>
                    <th>Total</th>
                </tr>
        </thead>
        <tbody>
        {% for item in order.items.all %}
            <tr class="row{% cycle '1' '2' %}">
                <td>{{ item.product.name }}</td>
                <td class="num">{{ item.price }} DA</td>
                <td class="num">{{ item.quantity }}</td>
                <td class="num"> {{ item.get_cost }} DA</td>
            </tr>
        {% endfor %}
            <tr class="total">
                <td colspan="3">Total</td>
                <td class="num">{{order.get_total_cost}} DA</td>
            </tr>
        </tbody>
    </table>
</div>
{% endblock %}