cart/urls.py
from django.urls import path
from .views import  cart_detail,  cart_add, cart_remove, cart_product_update, cart_one_add

app_name = 'cart'

urlpatterns = [
   path('', cart_detail, name='cart_detail'),
   path('cart_one_add/<int:product_id>/', cart_one_add, name='cart_one_add'),
   # path('checkout', CheckoutView.as_view(), name='CheckoutView'),
   path('add/<int:product_id>/', cart_add, name='cart_add'),
   # path('ajouter-au-panier', cart_add_one_product, name='cart_add_one_product'),
   path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
   path('update/', cart_product_update, name='cart_product_update'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from config import settings
from django.conf.urls.static import static


urlpatterns = [

    path('', include("core.urls")),
    path('', include("business.urls")),
    path('cart/', include("cart.urls")),
    path('orders/', include("order.urls")),
    path('coupons/', include("coupons.urls")),
    path('delivery/', include("delivery.urls")),
    # path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    # path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),
    urlpatterns += path('admin/', admin.site.urls),
else:
    urlpatterns += path('sunlab-admin/', admin.site.urls),

core/urls.py
from django.urls import path, re_path
from .views import IndexView, AboutView, ContactView,  ProductsView, ProductsView, ProductDetailView, VirementBancaireView, CarteBancaireView ,PaiementView ,PaiementEspecesView ,EchangeView ,LivraisonView ,RetourView,  product_detail, filtred_htmx_products, sorted_htmx_products

app_name = 'core'

urlpatterns = [

    path('', IndexView.as_view(), name='index'),
    path('produits/', ProductsView.as_view(), name='products'),
    # path('filtres-produits/', filtered_view, name='filtered-products'),
    path('produits-filtered/', filtred_htmx_products, name='filtered-products'),
    path('produits-sorted/', sorted_htmx_products, name='sorted-products'),
    path('product-detail/', product_detail, name='product-detail'),

    # path('produits/<slug:slug>/', CategoryProductsView.as_view(), name='prod-by-cat'),
    # path('produits/<slug:slug>/', CategoryProductsView.as_view(), name='prod-by-sub-cat'),
    path('produits/produit/<slug:slug>/', ProductDetailView.as_view(), name='productDetail'),


    path('contact/', ContactView.as_view(), name='contact'),
    path('about/', AboutView.as_view(), name='about'),
    #  PAIEMENT URLS

    path('virement-bancaire/', VirementBancaireView.as_view(), name='virement-bancaire'),
    path('carte-bancaire/', CarteBancaireView.as_view(), name='crte-bancaire'),
    path('paiement/', PaiementView.as_view(), name='paiement'),
    path('paiement-especes/', PaiementEspecesView.as_view(), name='paiement-especes'),
    #  Livraison URLS
    path('echange/', EchangeView.as_view(), name='echange'),
    path('livraison/', LivraisonView.as_view(), name='livraison'),
    path('retour/', RetourView.as_view(), name='retour'),

]

core/forms.py
from django import forms
from .models import ContactForm

class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactForm
        fields = ['name','phone','email','subject','message']

core/views.py
from django.db.models import Q
from django.http.response import HttpResponse 
from django.db.models.query import QuerySet
from django.shortcuts import get_object_or_404, render
from django.http import JsonResponse, request
from .forms import ContactForm
from delivery.models import Wilaya, Commune
from django.views.generic import TemplateView, DetailView, ListView, CreateView, View
from .models import Brand, Gamme, Product, Category, Tag
from business.models import Business, ThreePhotos, Slide, DualBanner, Counter, LargeBanner, SEO
from cart.forms import CartAddProductForm
from business.models import Counter
from .filters import ProductFilter
from django.core.paginator import Paginator
from django.template.loader import render_to_string
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from cart.forms import CartAddProductForm
from django.db.models import F
from django.core.management.utils import get_random_secret_key


class IndexView(TemplateView):
    template_name = "index.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["new_products"] = Product.objects.filter(new=True, actif=True)[:10]
        context["top_products"] = Product.objects.filter(top=True, actif=True)[:10]
        context["big_slides"]   = Slide.objects.filter(actif=True)
        context["three_photos"] = ThreePhotos.objects.all()[:3]
        context["large_banner"] = LargeBanner.objects.last()
        context["random_cat"]   = Category.objects.filter(actif=True)
        context["home_balises"] = SEO.objects.filter(actif=True, only_home_page=True)
        
        print(get_random_secret_key())
        all_cat = Category.objects.filter(actif=True)
        cat_list = []
        for cat in all_cat:
            if cat.products.all().count() > 0:
                cat_list.append(cat)
        print('categories ', cat_list)
        context["random_cat"] = cat_list[:3]
        print('a tchou hadi', context["random_cat"])

        if DualBanner.objects.filter(actif=True).count() >= 2:
            context["dual_banners"] = DualBanner.objects.filter(actif=True)[:2]
        return context


class AboutView(TemplateView):
    template_name = "about.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["counters"] = Counter.objects.filter(actif=True)[:4]
        return context

class VirementBancaireView(TemplateView):
    template_name = "paiement/virement-bancaire.html"

class CarteBancaireView(TemplateView):
    template_name = "paiement/carte-bancaire.html"

class PaiementView(TemplateView):
    template_name = "paiement/paiement.html"

class PaiementEspecesView(TemplateView):
    template_name = "paiement/paiement-especes.html"



class EchangeView(TemplateView):
    template_name = "livraison/echange.html"

class LivraisonView(TemplateView):
    template_name = "livraison/livraison.html"

class RetourView(TemplateView):
    template_name = "livraison/retours.html"


def product_detail(request):
    product = Product.objects.get(id=Product.objects.first().id)
    return render(request, 'snippets/product-modal.html', {'product': product})


class ProductsView(ListView):
    context_object_name = 'products'
    model = Product
    template_name = "products.html"
    paginate_by = 24
    def get_queryset(self):
        try:
            print('tryyy')
            param = self.request.GET.get('category')
            print('category', param)
            if param == 'all':
                category = Category.objects.filter(actif=True)
                products = Product.objects.filter(actif=True)
            elif param is None:
                category = Category.objects.filter(actif=True)
                products = Product.objects.filter(actif=True)
            else:
                category = Category.objects.get(id = param)
                products = Product.objects.filter(category__in=category.get_descendants(include_self=True))
            new = self.request.GET.get('new')
            if new == 'new':
                print('newww')
                products = Product.objects.filter(new=True)
            elif new == 'promo':
                print('promooooo')
                products = Product.objects.filter(old_price__isnull=False)
            else:
                pass
        except:
            print('exceeeept')
            try:
                new = self.request.GET.get('new')
                if new == 'new':
                    print('newww')
                    products = Product.objects.filter(new=True)
                elif new == 'promo':
                    print('promooooo')
                    products = Product.objects.filter(old_price=True)
                else:
                    pass
            except:
                category = Category.objects.filter(actif=True)
                products = Product.objects.filter(actif=True)
        query = self.request.GET.get('name')
        if query:
            # print('query', query)
            qs = products.search(query=query)
            # print('les produits ')
        else:
            # print('les ELSEEEE ', products)
            qs = products
        return qs
        # except:
        #     print(' kamel les produits kharjou :) excepty !!!')
        #     return super().get_queryset() 
        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.GET.get('category'):
            try:
                category = self.request.GET.get('category')
                if category == 'all':                
                    context["category"] = Category.objects.filter(actif=True)
                else:                
                    context["category"] = Category.objects.get(id = category)
            except:
                pass
        # context["tags"] = Tag.objects.all()
        # context["brands"] = Brand.objects.filter(actif=True)
        # gammes = Gamme.objects.all()
        context["gammes"] = Gamme.objects.filter(actif=True)
        context["filters"] = ProductFilter(self.request.GET, queryset= self.get_queryset())
        context["tags"] = Tag.objects.all()
        # context["products"] = Product.objects.all()
        return context


def filtred_htmx_products(request):
    context = {} 
    # print('request', request.GET)
    products = ProductFilter(request.GET, queryset= Product.objects.all())
    context['products'] = products.qs[:30]
    context['filter'] = products
    print('context[products]', context['products'])
    return render(request, 'snippets/htmx_products.html', context)

# def sorted_htmx_products(request):
#     context = {}
#     params= request.GET.get('order_by','')
#     print('request.GET', request.GET)
#     print('request params', request.GET.get('order_by'))
#     print('requestccccc', params)
#     if params == "name_a":
#         querySet = Product.objects.all().order_by('name')
#     elif params == "name_z":
#         querySet = Product.objects.all().order_by('-name')
#     elif params == "price":
#         querySet = Product.objects.all().order_by('price')
#     elif params == "brand":
#         querySet = Product.objects.all().order_by('gamme_brand')
#     else:
#         print('je sui laaa')
#         querySet = Product.objects.all()
#     products = ProductFilter(request.GET, queryset=querySet )
#     print('sorted products', products.qs)
#     context['products'] = products.qs
#     return render(request, 'snippets/htmx_products.html', context)
    # return HttpResponse('hello')

def sorted_htmx_products(request):
    context = {}
    print('request.GET', request.GET)
    print('request params', request.GET.get('order_by'))

    querySet = Product.objects.all()
    products = ProductFilter(request.GET, queryset=querySet )
    print('sorted products', products.qs)
    context['products'] = products.qs
    # return render(request, 'snippets/htmx_products.html', 0context)
    return HttpResponse('hello')



class ProductDetailView(DetailView):
    model = Product
    context_object_name = 'product'
    template_name = "product-detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["related"] = Product.objects.filter(actif=True).order_by('?')[:4] 
        context["wilayas"] = Wilaya.objects.all().order_by('name') 
        prod = self.get_object()
        category = prod.category
        products =  Product.objects.filter(category = category)
        context["related_products"] = products.exclude(id= prod.id).order_by('?')[:8]
        context["related_products_count"] = products.count() - 1
        context['form'] = CartAddProductForm()
        # context['atributes'] = prod.product_type.atributes.all()
        return context
    

class ContactView(CreateView):
    template_name = 'contact.html'
    form_class = ContactForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context
  
    def post(self, request, *args, **kwargs):
        form = ContactForm(request.POST)
      
        message = 'Une erreur est survenue, veuillez réessayer.'
        success = False
        try:
            #save the form   
            if form.is_valid():
                form.save()
                #messages.success(request, 'Votre message a bien été envoyé')
                message = 'Votre message a bien été envoyé!'
                success = True
                print(success)
                return render(request, 'other/contact.html', {'message': message, 'success': success})
            else:
                print(success)
                message = 'Une erreur est survenue, veuillez réessayer.'
                return render(request, 'contact.html', {'message': message, 'failure': True})
        except:
            return render(request, 'contact.html', {'message': message, 'failure': True})

core/templates/snippets/htmx_products.html
{% load static %}
<div class="col-lg-9 order-1 order-lg-2" id="removed-products">
    <div class="single-banner shop-page-banner">
        <div class="row">
            {% for cat in category.get_children %}
                <div class="col-sm-6 col-md-4">
                    <a href="{{cat.get_absolute_url}}">
                    <div class="cat-box pt-3 d-flex" >
                            <span class="d-inline-block pr-10">
                                <span class="d-flex category-span">
                                    {% if cat.icon %}
                                        <img class="d-block img-fluid" src="{{cat.icon.url}}" alt="{{cat.name}}">
                                    {% else %}
                                        <img class="d-block img-fluid" src="{% static "images/icons/category.png" %}" alt="pas icon">
                                    {% endif %}
                                </span>
                            </span>
                            <span class="align-middle d-inline-block text text-uppercase">{{cat.name}}</span>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="shop-products-wrapper">
        <div class="shop-top-bar mt-30">
            <div class="shop-bar-inner">
                <div class="product-view-mode">
                    <ul class="nav shop-item-filter-list" role="tablist">
                        <li class="active" role="presentation"><a aria-selected="true" class="active show" data-toggle="tab" role="tab" aria-controls="grid-view" href="#grid-view"><i class="fa fa-th"></i></a></li>
                        <li role="presentation"><a data-toggle="tab" role="tab" aria-controls="list-view" href="#list-view"><i class="fa fa-th-list"></i></a></li>
                    </ul>
                </div>
                <div class="toolbar-amount">
                    <span>{{products.count}} produit trouver </span>
                </div>
            </div>
            <!-- <div class="product-select-box">
                <form id="ordering-form" hx-get="{% url 'core:sorted-products' %}" hx-trigger="changed" hx-target="#removed-products" hx-swap="innerHTML">
                    <div class="product-short" >
                        <p>Trier par:</p>
                        <select id="ordering" name="order_by" class="nice-select" >
                            <option value="default">Default</option>
                            <option value="name">Nom (A - Z)</option>
                            <option value="-name">Nom (Z - A)</option>
                            <option value="price">Prix</option>
                            <option value="gamme__brand">Marque</option>
                        </select>
                    </div>
                </form>
            </div> -->
        </div>
        <div class="tab-content">
            <div id="grid-view" class="tab-pane fade active show" role="tabpanel">
                <div class="product-area shop-product-area">
                    <div class="row">
                        {% for product in products %}
                            <div class="col-lg-4 col-md-4 col-sm-6 mt-40">
                                {% include "snippets/product-block.html" %}
                            </div>
                        {% empty %}
                            <center><h4 style="margin-left: 25%;margin-top: 10%;">Aucun produit trouver pour votre recherche</h4></center>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div id="list-view" class="tab-pane fade product-list-view" role="tabpanel">
                <div class="row">
                    <div class="col">
                        {% for product in products %}
                            {% include "snippets/product-list-view.html" %}
                        {% empty %}
                        <center><h4 style="margin-left: 25%;margin-top: 10%;">Aucun produit trouver pour votre recherche</h4></center>
                        {% endfor %}
                    </div>
                </div>
            </div>
            {% if page_obj %}
              
                <div class="paginatoin-area">
                    <div class="row">
                        {% if page_obj.start_index %}
                        <div class="col-lg-6 col-md-6 pt-xs-15">
                            <p> {{ page_obj.start_index }} à {{ page_obj.end_index }} de {{page_obj.paginator.count}} Produits</p>
                        {% endif %}
                        </div>
                        <div class="col-lg-6 col-md-6">
                            <ul class="pagination-box pt-xs-20 pb-xs-15">
                                {% if page_obj.has_previous %}
                                    <li><a href="?page={{ page_obj.previous_page_number }}" class="Previous"><i class="fa fa-chevron-left"></i> Précédent</a>
                                {% endif %}

                                </li>
                                    {% for page in page_obj.paginator %}
                                        <li {% if page.number == page_obj.number %} class="active" {% endif %}><a href="?page={{page.number}}">{{page.number}}</a></li>
                                    {% endfor %}
                                {% if page_obj.has_next %}
                                    <li><a href="?page={{ page_obj.next_page_number }}" class="Next"> Suivant <i class="fa fa-chevron-right"></i></a></li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
            {% endif %}

        </div>
    </div>
</div>

core/templates/snippets/product-block.html
{% load i18n %} 
{% load static %}
<div class="single-product-wrap">
    <div class="product-image d-flex justify-content-center">
        <a href="{{product.get_absolute_url}}">
            <img class=""
            {% if product.photos.all.0 %}
                src="{{product.photos.all.0.fichier.url}}" alt="{{product.name}}">
            {% else %}
                src="{% static "images/pas-images.png" %}" alt="Pas de photo pour le moment">
            {% endif %}
        </a>
        {% if product.new  %}
            <span class="sticker">New</span>
        {% endif %}
    </div>
    <div class="product_desc">
        <div class="product_desc_info">
            <div class="product-review">
                <h5 class="manufacturer d-flex justify-content-between">
                    <a href="{{product.category.get_absolute_url}}">{{product.category}}</a>
                    {% if product.brand %}
                        <a href="{{product.category.get_absolute_url}}">{{product.brand}}</a>
                    {% endif %}
                </h5>
            </div>
            <h4><a class="product_name" href="{{product.get_absolute_url}}">{{product.name|truncatewords:4}}</a></h4>
            <div class="price-box">
                <span class="new-price new-price-2">{{product.price}} DA</span>
                {% if product.old_price %}
                    <span class="old-price">{{product.old_price}}</span>
                    <span class="discount-percentage">{{product.promo}}%</span>
                {% endif %}
            </div>
        </div>
        <div class="add-actions d-none d-md-block">
            <form id="add_one_cart" hx-target=".hm-minicart" hx-swap="outerHTML" class="block2-btn-addcart">
                {% csrf_token %}
                <ul class="add-actions-link d-flex justify-content-center">
                    <li class="add-cart active" ><a hx-post="{% url 'cart:cart_one_add' product.id %}" class="block2-name" >Ajouter au panier</a></li>
                </ul>
            </form>
        </div>
    </div>
</div>


 {% block extrajs %}
 <script>
    $('.block2-btn-addcart').each(function(){
        var nameProduct = $(this).parent().parent().parent().parent().find('.product_name').html();
        $(this).on('click', function(){
            swal(nameProduct, "Ajouté au panier", "success");
        });
    });
</script>
 {% endblock extrajs %}

core/templates/snippets/product-list-view.html
{% load i18n %} 
{% load static %}
<div class="row product-layout-list">
    <div class="col-lg-3 col-md-5 ">
        <div class="product-image">
            <a href="{{product.get_absolute_url}}">
                <img 
                {% if product.photos.all.0 %}
                    src="{{product.photos.all.0.fichier.url}}" alt="{{product.name}}">
                {% else %}
                    src="{% static "images/pas-images.png" %}" alt="Pas de photo pour le moment">
                {% endif %}
            </a>
            {% if product.status == 'N' %}
                <span class="sticker">New</span>
            {% endif %}
        </div>
    </div>
    <div class="col-lg-5 col-md-7">
        <div class="product_desc">
            <div class="product_desc_info">
                <div class="product-review">
                    <h5 class="manufacturer">
                        <a href="{{product.category.get_absolute_url}}">{{product.category}}</a>
                    </h5>
                </div>
                <h4><a class="product_name" href="{{product.get_absolute_url}}">{{product.name}}</a></h4>
                <div class="price-box mb-3">
                    <span class="new-price new-price-2">{{product.price}} DA</span>
                    {% if product.old_price %}
                        <span class="old-price">{{product.old_price}} DA</span>
                        <span class="discount-percentage">{{product.promo}}%</span>
                    {% endif %}
                </div>
                {% if product.text %}
                    <p>{{product.text}}</p>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="shop-add-action mb-xs-30">
            <ul class="add-actions-link">
                <li style="width: 100%;" class="add-cart"><a href="#">Ajouter au panier</a></li>
                <li><a class="quick-view" data-toggle="modal" data-target="#exampleModalCenter" href="#"><i class="fa fa-eye"></i>Vue Rapide</a></li>
            </ul>
        </div>
    </div>
</div>