cart/urls.py
from django.urls import path
from .views import  cart_detail,  cart_add, cart_remove, cart_product_update, cart_one_add

app_name = 'cart'

urlpatterns = [
   path('', cart_detail, name='cart_detail'),
   path('cart_one_add/<int:product_id>/', cart_one_add, name='cart_one_add'),
   # path('checkout', CheckoutView.as_view(), name='CheckoutView'),
   path('add/<int:product_id>/', cart_add, name='cart_add'),
   # path('ajouter-au-panier', cart_add_one_product, name='cart_add_one_product'),
   path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
   path('update/', cart_product_update, name='cart_product_update'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from config import settings
from django.conf.urls.static import static


urlpatterns = [

    path('', include("core.urls")),
    path('', include("business.urls")),
    path('cart/', include("cart.urls")),
    path('orders/', include("order.urls")),
    path('coupons/', include("coupons.urls")),
    path('delivery/', include("delivery.urls")),
    # path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    # path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar
    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),
    urlpatterns += path('admin/', admin.site.urls),
else:
    urlpatterns += path('sunlab-admin/', admin.site.urls),

core/urls.py
from django.urls import path, re_path
from .views import IndexView, AboutView, ContactView,  ProductsView, ProductsView, ProductDetailView, VirementBancaireView, CarteBancaireView ,PaiementView ,PaiementEspecesView ,EchangeView ,LivraisonView ,RetourView,  product_detail, filtred_htmx_products, sorted_htmx_products

app_name = 'core'

urlpatterns = [

    path('', IndexView.as_view(), name='index'),
    path('produits/', ProductsView.as_view(), name='products'),
    # path('filtres-produits/', filtered_view, name='filtered-products'),
    path('produits-filtered/', filtred_htmx_products, name='filtered-products'),
    path('produits-sorted/', sorted_htmx_products, name='sorted-products'),
    path('product-detail/', product_detail, name='product-detail'),

    # path('produits/<slug:slug>/', CategoryProductsView.as_view(), name='prod-by-cat'),
    # path('produits/<slug:slug>/', CategoryProductsView.as_view(), name='prod-by-sub-cat'),
    path('produits/produit/<slug:slug>/', ProductDetailView.as_view(), name='productDetail'),


    path('contact/', ContactView.as_view(), name='contact'),
    path('about/', AboutView.as_view(), name='about'),
    #  PAIEMENT URLS

    path('virement-bancaire/', VirementBancaireView.as_view(), name='virement-bancaire'),
    path('carte-bancaire/', CarteBancaireView.as_view(), name='crte-bancaire'),
    path('paiement/', PaiementView.as_view(), name='paiement'),
    path('paiement-especes/', PaiementEspecesView.as_view(), name='paiement-especes'),
    #  Livraison URLS
    path('echange/', EchangeView.as_view(), name='echange'),
    path('livraison/', LivraisonView.as_view(), name='livraison'),
    path('retour/', RetourView.as_view(), name='retour'),

]

core/models.py
from django.db import models
from django.db.models.aggregates import Variance
from django.utils.text import slugify
# Create your models here.
from django.urls import reverse
from tinymce import models as tinymce_models
from django.utils.translation import gettext_lazy as _
from django.shortcuts import redirect
from django.db.models import Q

from django.db import models
from mptt.models import MPTTModel, TreeForeignKey

STATUS_PRODUIT = (
    ('N', _('Normal')),
    ('R', _('Rupture')),
    ('P', _('Promotion')),
)

class ActiveManager(models.Manager):
    def active(self):
        return self.filter(active=True)

class Tag(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name
        
class ProductQuerySet(models.QuerySet):
    def search(self, query=None):
        if query is None or query == "":
            return self.none()
        lookups = (
            Q(name__icontains=query) |
            Q(reference__icontains=query) |
            Q(gamme__brand__name__icontains=query) |
            # Q(product_type__name__icontains=query) |
            Q(category__name__icontains=query) |
            Q(text__icontains=query) & Q(actif=True)
        )
        return self.filter(lookups) 

class ProductManager(models.Manager):
    def get_queryset(self):
        return ProductQuerySet(self.model, using=self._db)

    def search(self, query=None):
        return self.get_queryset().search(query=query)

class Brand(models.Model):
    name = models.CharField(max_length=150, verbose_name='Nom')
    actif = models.BooleanField(verbose_name='actif', default=True)
    def __str__(self):
        return self.name
    def products_count(self):
        return Product.objects.filter(gamme__brand_id=self.id).count()
    class Meta:
        ordering = ('id',)
        verbose_name = '- Marque'
        verbose_name_plural = '- Marques'

class Gamme(models.Model):
    name = models.CharField(max_length=150, verbose_name='Nom')
    brand = models.ForeignKey(Brand, related_name="gammes", on_delete=models.CASCADE, blank=True, null=True)

    actif = models.BooleanField(verbose_name='actif', default=True)
    objects = ActiveManager()
    def __str__(self):
        return self.name

    class Meta:
        ordering = ('id',)
        verbose_name = '- Gamme'
        verbose_name_plural = '- Gammes'


class Category(MPTTModel):
    name  = models.CharField( max_length=150, verbose_name='Nom')
    slug  = models.SlugField( max_length=150, unique= True, verbose_name='URL')
    actif = models.BooleanField(verbose_name='actif', default=True)
    icon  = models.ImageField(upload_to='images/categories', null=True, blank=True)
    # tree = models.ForeignKey(Tree, verbose_name="Branche de Catégorie",related_name="sub_categories" ,on_delete=models.CASCADE)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')
    objects = ActiveManager()

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('id',)
        verbose_name = 'Catégorie'
        verbose_name_plural = '- Catégories'
    class MPTTMeta:
        order_insertion_by = ["name"]
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name +'-'+str(self.id))
        return super(Category, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return f"/produits/?category={self.id}"


class ProductType(models.Model):
    """
    ProductType Table will provide a list of the different types
    of products that are for sale.
    """
    name = models.CharField(verbose_name=_("Type"), help_text=_("Required"), max_length=255, unique=True)
    actif = models.BooleanField(default=True)
    class Meta:
        verbose_name = _("- Produits Type")
        verbose_name_plural = _("- Produits Types")
    def __str__(self):
        return self.name


class Atribute(models.Model):
    name = models.CharField(verbose_name=_("Atribut"), help_text=_("Required"), max_length=255)
    product_type = models.ForeignKey(ProductType, related_name="atributes",on_delete=models.CASCADE)
    class Meta:
        verbose_name = _("Produits Specification")
        verbose_name_plural = _("Produits Specifications")
    def __str__(self):
        return self.name

class Product(models.Model):
    name         = models.CharField( max_length=200, verbose_name='Nom')
    slug         = models.SlugField( max_length=150, unique= True, verbose_name='URL')
    reference    = models.CharField( max_length=200, verbose_name='Référence', unique=True, blank=True, null=True)
    category     = TreeForeignKey(Category, verbose_name="Catégorie",related_name="products" ,on_delete=models.CASCADE, blank=True, null=True)
    product_type = models.ForeignKey(ProductType, on_delete=models.RESTRICT, blank=True, null=True)
    gamme        = models.ForeignKey(Gamme, blank=True, null=True,related_name="products", on_delete=models.CASCADE)
    text         = models.TextField(verbose_name='petit text', blank=True, null=True)
    price        = models.DecimalField(max_digits=10, decimal_places=2, default=1)
    old_price    = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Ancien prix",blank=True, null=True)
    actif        = models.BooleanField(verbose_name='actif', default=True)
    new          = models.BooleanField(verbose_name='Nouveau', default=False)
    top          = models.BooleanField(verbose_name='Meilleur vente', default=False)
    status       = models.CharField(choices=STATUS_PRODUIT, max_length=1, default='N', blank=True, null=True, verbose_name='Status')
    stock        = models.IntegerField( default=1,  verbose_name="Stock initial",blank=True, null=True)
    created      = models.DateTimeField(verbose_name='Date de Création', auto_now_add=True)
    updated      = models.DateTimeField(verbose_name='Date de dernière mise à jour', auto_now=True)
    description  = tinymce_models.HTMLField(verbose_name='Déscription du produit', blank=True, null=True)
    tag          = models.ManyToManyField(Tag, blank=True)

    # brand           = models.ForeignKey(Brand, related_name="brand_products", on_delete=models.CASCADE, blank=True, null=True)
    
    objects = ProductManager()
    
    def __str__(self):
        return self.name

    class Meta:
        ordering = ('id',)
        verbose_name = 'Produit'
        verbose_name_plural = '- Produits'
    # def save(self, *args, **kwargs):
    #     if self.slug is None:
    #         self.slug = slugify(self.name +'-'+str(self.id))
    #         return super(Product, self).save(*args, **kwargs)    
    def promo(self):
        try:
            pourcentage = (self.price / self.old_price) * 100 -100
            return int(pourcentage)
        except:
            return None
    def get_absolute_url(self):
        return reverse("core:productDetail", args=[self.slug])


class ProductDetail(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="specifications")
    key =   value = models.CharField(verbose_name=_("Carectéristique"),help_text=_("Atribute Value(maximum of 255 words"),max_length=255,)
    value = models.CharField(
        verbose_name=_("Valeur"),
        help_text=_("Atribute Value(maximum of 255 words"),
        max_length=255,
    )
    class Meta:
        verbose_name = _("Produit Details")
        verbose_name_plural = _("Produit Details")

    def __str__(self):
        return self.value

class AtributesValue(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    specification = models.ForeignKey(Atribute, related_name='values',on_delete=models.RESTRICT)
    stock = models.IntegerField(verbose_name='Stock', default=1)
    value = models.CharField(
        verbose_name=_("value"),
        help_text=_("Atribute Value(maximum of 255 words"),
        max_length=255,
    )
    class Meta:
        verbose_name = _("Atribute Value")
        verbose_name_plural = _("Atribute Values")
    def __str__(self):
        return self.value

class PhotoProduct(models.Model):
    fichier   = models.ImageField(upload_to='images/produits') 
    actif   = models.BooleanField(verbose_name='actif', default=True)
    produit = models.ForeignKey(Product, related_name="photos", on_delete=models.CASCADE)


class ProductDocument(models.Model):
    file    = models.FileField(upload_to='images/produits') 
    name    = models.CharField(verbose_name=_("Nom du document") , max_length=25)
    actif   = models.BooleanField(verbose_name='actif', default=True)
    produit = models.ForeignKey(Product, related_name="documents", on_delete=models.CASCADE)

class ContactForm(models.Model):
    name        = models.CharField(verbose_name=_('Nom complet'), max_length=100)
    phone       = models.CharField(verbose_name=_("Téléphone") , max_length=25)
    email       = models.EmailField(verbose_name=_("Email"), null=True, blank = True)
    subject     = models.CharField(verbose_name=_("Sujet"), max_length=50, blank=True)
    message     = models.TextField(verbose_name=_("Message"), blank=True, null=True)
    date_sent = models.DateTimeField(verbose_name=_("Date"), auto_now_add=True)

    def __str__(self):
        return self.name
    class Meta:
        ordering = ('id',)
        verbose_name = 'Formulaire de contact'
        verbose_name_plural = 'Formulaire de contact'

core/forms.py
from django import forms
from .models import ContactForm

class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactForm
        fields = ['name','phone','email','subject','message']

core/templates/about.html
{% extends "base.html" %}
{% load static %}
{% block content %}
            <!-- Begin Li's Breadcrumb Area -->
            <div class="breadcrumb-area">
                <div class="container">
                    <div class="breadcrumb-content">
                        <ul>
                            <li><a href="{% url 'core:index' %}">Accueil</a></li>
                            <li class="active">A propos</li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- Li's Breadcrumb Area End Here -->
            <!-- about wrapper start -->
            <div class="about-us-wrapper pt-60 pb-40">
                <div class="container">
                    <div class="row">
                        <!-- About Text Start -->
                        <div class="col-lg-6 order-last order-lg-first">
                            <div class="about-text-wrap">
                               {{business.about|safe}}
                            </div>
                        </div>
                        <!-- About Text End -->
                        <!-- About Image Start -->
                        <div class="col-lg-5 col-md-10">
                            <div class="about-image-wrap">
                                {% if business.about_photo %}
                                    <img src="{{business.about_photo.url}}" alt="a propode {{business.name}}" srcset="photo a propos">
                                {% else %}
                                    <img class="img-full" src="{% static "images/700.jpg" %}" alt="A propos de nous" />
                                {% endif %}
                            </div>
                        </div>
                        <!-- About Image End -->
                    </div>
                </div>
            </div>
            <!-- about wrapper end -->
            <!-- Begin Counterup Area -->
            <div class="counterup-area">
                <div class="container-fluid p-0">
                    <div class="row no-gutters">
                        {% for counter in counters %}
                            <div class="col-lg-3 col-md-6">
                                <div class="limupa-counter white-smoke-bg">
                                    <div class="container">
                                        <div class="counter-img">
                                            <img src="{{counter.icon.url}}" width="60" alt="{{counter.name}}">
                                        </div>
                                        <div class="counter-info">
                                            <div class="counter-number">
                                                {% if counter.before %}
                                                    <h3 style="display: inline-block;">{{counter.before}}</h3>
                                                {% endif %}
                                                <h3 style="display: inline-block;" class="counter">{{counter.number}}</h3>
                                            </div>
                                            <div class="counter-text">
                                                <span>{{counter.name}}</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
{% endblock content %}

core/templates/contact.html
{% extends "base.html" %}
{% load static %}
{% block content %}
            <!-- Begin Li's Breadcrumb Area -->
            <div class="breadcrumb-area">
                <div class="container">
                    <div class="breadcrumb-content">
                        <ul>
                            <li><a href="{% url 'core:index' %}">Accueil</a></li>
                            <li class="active">Contact</li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- Li's Breadcrumb Area End Here -->     
            <!-- Begin Contact Main Page Area -->
            <div class="contact-main-page mt-60 mb-40 mb-md-40 mb-sm-40 mb-xs-40">
                <div class="container mb-60">
                    {% if business.google_maps %}
                    <div id="google-map">
                        {{business.google_maps|safe}}
                    </div>
                    {% endif %}
                </div>
                <div class="container">
                    <div class="row">
                        <div class="col-lg-5 offset-lg-1 col-md-12 order-1 order-lg-2">
                            <div class="contact-page-side-content">
                                <h3 class="contact-page-title">Contactez nous</h3>
                                <p class="contact-page-message mb-25">{{business.contact_message}}</p>
                                <div class="single-contact-block">
                                    <h4><i class="fa fa-fax"></i> Addresse</h4>
                                    <p>{{business.adress}}</p>
                                </div>
                                <div class="single-contact-block">
                                    <h4><i class="fa fa-phone"></i> Téléphone</h4>
                                    <p>{{business.phone}}</p>
                                    <p>{{business.phone2}}</p>
                                </div>
                                <div class="single-contact-block last-child">
                                    <h4><i class="fa fa-envelope-o"></i> Emails</h4>
                                    {% if business.email %}
                                        <p>{{business.email}}</p>
                                    {% endif %} 
                                    {% if business.email2 %}
                                        <p>{{business.email2}}</p>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-12 order-2 order-lg-1">
                            <div class="contact-form-content pt-sm-55 pt-xs-55">
                                <h3 class="contact-page-title">Laisser Un Message</h3>
                                <div class="contact-form">
                                    <form action="{% url 'core:contact' %}" method=POST >
                                        {% csrf_token %}
                                        <div class="form-group">
                                            <label>Votre Nom<span class="required">*</span></label>
                                            <input type="text" name="name" id="customername" required>
                                        </div>
                                        <div class="form-group">
                                            <label>Votre Email <span class="required">*</span></label>
                                            <input type="email" name="email" id="customerEmail" required>
                                        </div>
                                        <div class="form-group">
                                            <label>Téléphone<span class="required">*</span></label>
                                            <input type="phone" name="phone" id="customerPhone" required>
                                        </div>
                                        <div class="form-group">
                                            <label>Sujet</label>
                                            <input type="text" name="subject" id="contactSubject">
                                        </div>
                                        <div class="form-group mb-30">
                                            <label>Votre Message</label>
                                            <textarea name="message" id="message" ></textarea>
                                        </div>
                                        <div class="form-group">
                                            <button type="submit" value="submit" id="submit" class="li-btn-3" name="submit">Envoyer</button>
                                        </div>
                                    </form>
                                </div>
                                <p class="form-messege"></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Contact Main Page Area End Here -->
         

<!-- contact32:04-->
{% endblock %}

core/templates/products.html
{% extends "base.html" %}
{% load static %}
{% load mptt_tags %}

{% block content %}
            <!-- Begin Li's Breadcrumb Area -->
            {% if category %}
                {% if request.GET.category != 'all' %}
                    <div class="breadcrumb-area">
                        <div class="container">
                            <div class="breadcrumb-content">
                                <ul>
                                    <li><a href="{% url 'core:index' %}">Acceuil</a></li>
                                    {% for cat in category.get_ancestors %}
                                    <li><a href="{{cat.get_absolute_url}}">{{cat.name}}</a></li>
                                    {% endfor %}
                                    <li class="active">{{category.name}}</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endif %}
            <!-- Li's Breadcrumb Area End Here -->
            <!-- Begin Li's Content Wraper Area -->
            <div class="content-wraper pt-60 pb-60 pt-sm-30">
                <div class="container">
                    <div class="row">
                        {% include "snippets/htmx_products.html" %}
                        <div class="col-lg-3 order-2 order-lg-1">
                            <form method="GET" hx-get="{% url 'core:filtered-products' %}" hx-trigger="change" hx-target="#removed-products" hx-swap="outerHTML"> 
                                <div class="sidebar-categores-box mt-sm-30 mt-xs-30">
                                    <input type="text" name="name" placeholder="Recherchez..." >
                                </div>
                                <div class="sidebar-categores-box mt-sm-30 mt-xs-30">
                                    <div class="sidebar-title">
                                        <h2>Trier par</h2>
                                    </div>
                                    <select name="ordering" id="id_ordering" style="width: 100%;">
                                        <option value="default">Default</option>
                                        <option value="name">Nom (A - Z)</option>
                                        <option value="-name">Nom (Z - A)</option>
                                        <option value="price">Prix</option>
                                    </select>
                                </div>
                                <div class="sidebar-categores-box mt-sm-30 mt-xs-30">
                                    <div class="sidebar-title">
                                        <h2>Categories</h2>
                                    </div>
                                    <div class="category-sub-menu categori-checkbox">
                                        <ul>
                                            {% recursetree categories %}
                                                {% if node.children.count > 0 %}
                                                    <li class="has-sub text-uppercase"><a href="{{node.get_absolute_url}}" style="font-size: 15px;">{{node.name}}</a>
                                                        <ul>
                                                            {% for cat in node.children.all %}
                                                                <li>
                                                                    <input class="d-inline" type="checkbox" name="category" id="cat-{{cat.id}}" value="{{cat.id}}">
                                                                    <label class="d-inline text-uppercase" for="cat-{{cat.id}}">
                                                                        <span></span>
                                                                        {{cat.name}}
                                                                    </label>
                                                                </li>
                                                            {% endfor %}
                                                        </ul>
                                                    </li>
                                                {% endif %}
                                            {% endrecursetree %}
                                        </ul>
                                    </div>
                                </div>
                                <div class="sidebar-categores-box mt-sm-30 mt-xs-30">
                                    <div class="sidebar-title">
                                        <h2>Autres Filtres</h2>
                                    </div>
                                    <div class="category-sub-menu categori-checkbox">
                                        <ul>
                                            <li class="ml-5">
                                                <input type="checkbox" name="new" id="nouveaux" value="true">
                                                <label for="nouveaux">
                                                    <span></span>
                                                    Nouveaux Produits
                                                </label>
                                            </li>
                                            <li class="ml-5">
                                                <input type="checkbox" name="old_price" value="true" id="promotions" >
                                                <label for="promotions">
                                                    <span></span>
                                                    Promotions
                                                </label>
                                            </li>
                                            <li class="has-sub"><a href="#" style="font-size: 15px;">Gammes</a>
                                                <ul>
                                                    {% for gamme in gammes %}
                                                    {% if gamme.products.all.count > 0 %}
                                                        <li>
                                                            <input type="checkbox" name="gamme" id="gamme-{{gamme.id}}" value="{{gamme.id}}">
                                                            <label for="gamme-{{gamme.id}}">
                                                                <span></span>
                                                                {{gamme.name}}
                                                                <small>({{gamme.products.count}})</small>
                                                            </label>
                                                        </li>
                                                    {% endif %}
                                                {% endfor %}
                                                </ul>
                                            </li>
                                            <li class="has-sub"><a href="#" style="font-size: 15px;">Tags</a>
                                                <ul>
                                                    {% for tag in tags %}
                                                        {% if tag.product_set.all.count > 0 %}
                                                                <li>
                                                                    <input type="checkbox" name="tag" id="tag-{{tag.id}}" value="{{tag.id}}">
                                                                    <label for="tag-{{tag.id}}">
                                                                        <span></span>
                                                                        {{tag.name}}
                                                                        <small>({{tag.product_set.all.count}})</small>
                                                                    </label>
                                                                </li>
                                                        {% endif %}
                                                    {% endfor %}
                                                </ul>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                                <!-- <div class="apply-filters">
                                    <button class="filter-button" type="submit">Filtrer</button>
                                </div> -->
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Content Wraper Area End Here -->
{% endblock content %}
 